### ISSUE TITLE
Can u make it using package names instead of labels in cfg file

### ISSUE THREAD

**Issue by Levantosa** [zgfg/SystemlessDebloater#8]

**Comment by zgfg** [comment]
No. It is described in Readme and on XDA how to read log and compare PKG names with apk names.

Hence not necessary.
Generally, ppl don't need to know PKG names

Also, it will be a nightmare for all current users to rewrite their existing cfg files from apk names to PKG names

On the other side, it will be waste of time to implement to read two types of cfg files, with apk names and alternatively with PKG names

**Comment by Levantosa** [comment]
It's easy to find pckg name with just a simple command unless u need to know technical stuff to get label name,but it's not necessary, it may be easier for ur end users.

**Comment by zgfg** [comment]
> It's easy to find pckg name with just a simple command unless u need to know technical stuff to get label name,but it's not necessary, it may be easier for ur end users.

Rooting is not for everybody😁
Certain technical knowledge, ability to understand things and wish to learn must be assumed
